### ISSUE TITLE
패스트캠퍼스 강의 듣고 질문하고자 하는데, 여기에 해도 되나요?

### ISSUE THREAD

**Issue by hongym7** [jaewonlee-728/fastcampus-RecSys#2]
안녕하세요 혹시 패스트캠퍼스 강의 듣고 질문하고자 하는데, 여기에 해도 되나요?
혹시 다른 곳에 질문해야 한다면 다른 곳에 질문하겠습니다.

=============================================================================

"03. Ch 01. 딥러닝과 추천 알고리즘 - 03. Neural CF 실습" 강의 듣고 마지막에 'result_df' 에서 'pred_ratings' 의 값이 무의미하다고 말씀해주셨는데 왜 무의미 한지 이해가 안가서요.
딥러닝 모델을 통해 test의 값에 대한 predict를 한 값인데, 왜 무의미 한 값이지 궁금합니다.

**Comment by jaewonlee-728** [comment]
안녕하세요, 질문주셔서 감사합니다. 
`result_df`에서 `pred_ratings`가 무의미하다고 말씀드린 것은 다음과 같은 이유입니다. 
모델의 추천성능을 직접적으로 확인하고자 함이 아니라 모델학습과정을 설명드리는 것이 주된 목적이기 때문에 해당 결과를 통해서 NeuralCF는 이정도 성능을 나타내는구나라고 생각하는 것이 무의미하다는 뜻에서 말씀드렸습니다.
train set과 test set으로 나누어 학습을 했고, test set을 통해 모델의 성능 평가를 하는 과정 속에서 나타난 결과들은 의미가 있습니다. 
혼돈을 드려 죄송합니다. 혹시 추가로 궁금하신 부분 있으시면 말씀 부탁드리겠습니다. 감사합니다.

**Comment by hongym7** [comment]
빠른 답변 정말 감사드립니다.
그럼 predict 한 값과 실제 test 값이 많이 차이가 나는데, 
이 부분은 하이퍼 파라미터 튜닝 등으로 성능이 올라갈까요?

사실 하이퍼 파리미터가 많아서 어느 부분을 건드려야할지 감이 잘 안와서요
예를 들어 아래와 같이 많이 차이가 나서요
11242 user가 10102 movie 의 예측 rating : 4.975164 -> 실제 rating : 10

**Comment by jaewonlee-728** [comment]
넵, 그러나 하이퍼파라미터 튜닝으로 어느정도 성능 향상을 기대할 수는 있으나 지금과 같은 경우(예측 rating : 4.975164 -> 실제 rating : 10)처럼 큰 차이가 날때 하이퍼파라미터 튜닝만으로 충분한 성능을 기대하기는 어려울 것 같습니다. 
실습에 사용한 데이터셋으로 추천 성능을 향상 시키기 위해서 데이터 전처리(평점이 9,10점에 많이 쏠려 있는 현상)를 다시 해볼 수도 있을 것 같습니다. 데이터 크기에 맞춰 좀 더 간단한 모델 구조를 구현할 수도 있을 것이고, 논문과 마찬가지로 0과 1로 cross entropy loss를 활용하여 학습하는 방법도 있을 것 같습니다. NeuralCF가 아닌 다른 모델도 시도해보는 것도 방법입니다.

더 궁금하신 부분 있으시면 말씀 부탁드리겠습니다. 감사합니다.

**Comment by hongym7** [comment]
답변 감사합니다~
