### ISSUE TITLE
Wide_Deep Learning for Recommender System 실습 질문

### ISSUE THREAD

**Issue by hongym7** [jaewonlee-728/fastcampus-RecSys#3]
안녕하세요 질문드립니다

실습중 deep model 준비시 아래와 같이 column을 준비합니다.

> embed_cols = list(set([(x[0], 16) for x in cross_cols]))
> continuous_cols = ['year']

1. 수업에서 여러번 들었지만 'embedding' 이란 의미가 잘 이해가 안가서 그런데 알려주실 수 있나요?
2. continuous 하지 않은 항목은 'embedding'을 정의해주면 된다 라는 의미도 궁금합니다.
3. deep model은 무조건 continuous 한 column이 input으로 들어가야 하나요? 없다면 제외해도 상관없는건지요?

* 참고 : pytorch-widedeep 소스 변경에 따라 아래와 같이 0.4.7 버젼 사용해야 코드가 정상적으로 동작하네요
             !pip install pytorch-widedeep==0.4.7

감사합니다.

**Comment by jaewonlee-728** [comment]
안녕하세요, 질문주신 내용에 대해서 답변 드리겠습니다. 

1. `embedding`이란 벡터화하는 것이라고 생각하시면 됩니다. 데이터의 특징을 찾아서 그 특징을 벡터화한 것을 embedding이라고 일반적으로 표현합니다.
2. 범주형 자료를 연속형 벡터로 치환하는 것을 생각해보시면 좋을 것 같습니다.
3. deep과 wide의 의미가 어떤 형태의 feature를 model의 input으로 줄 것인지에 관련된 내용이기 때문입니다. 없다면 제외해도 상관없으나 그렇게 될 경우 wide&deep model이 아닌 하나의 형태만 갖는(ex. wide model)이 되겠습니다. 

추가로 임베딩, 연속형 변수, 범주형 변수 등에 관한 [설명 링크](https://blog.linewalks.com/archives/6408)를 첨부드립니다. 참고 부탁드립니다. 

답변이 늦어서 죄송합니다. 더 궁금하신 내용이 있으시다면 말씀 부탁드리겠습니다. 감사합니다.
