### ISSUE TITLE
Deep FM 관련 질문

### ISSUE THREAD

**Issue by hongym7** [jaewonlee-728/fastcampus-RecSys#4]
안녕하세요

Deep FM

1. Deep FM 설명시 low order feature interaction 와 high order feature interaction의 의미?

**Comment by jaewonlee-728** [comment]
안녕하세요, 질문주신 내용에 대한 답변은 아래와 같습니다.

low order feature interaction은 주로 order가 2인 경우를 나타내며, 이는 2개의 feature간의 interaction을 의미합니다. high order의 경우 더 많은 feature들간의 interaction을 의미하게 됩니다. 따라서 DeepFM에서 Deep Learning을 활용한 부분에서는 feature간의 더 복잡한 관계를 파악하고, FM부분에서는 2개 feature 사이의 interaction을 더 면밀하게 파악한다고 이해하시면 될 것 같습니다.

**Comment by hongym7** [comment]
감사합니다.
