### ISSUE TITLE
"리뷰데이터로 추천성능 끌어올리기 실습" 질문

### ISSUE THREAD

**Issue by hongym7** [jaewonlee-728/fastcampus-RecSys#5]
안녕하세요 질문사항이 너무 많네요 ㅠㅠ
양해 부탁드립니다.

해당 실습에서 결국 리뷰데이터를 통해 평점 예측이라는 작업을 수행하는데, 아마 리뷰데이터를 이런식으로 활용할 수 있다라는 것이 해당 실습의 목적이라고 생각합니다.
(사실 리뷰데이터로 평점 예측은 실제 추천시스템에 사용에는 조금 어폐가 있는 것 같아서요.
궂이 리뷰데이터로 평점을 예측하는 것은 무의미한 작업이라고 생각됩니다. 그래서 리뷰데이터에 대한 활용이 실습의 목적이라고 저도 생각하고요)

그런데 리뷰 데이터로 어떻게 추천시스템 성능 향상을 할 수 있을까요? 곰곰히 생각해봤는데 당장 떠오르는게 없어서요. 어떤 식으로 적용이 될지요. (리뷰데이터가 있다는 건 이미 평점을 줬다. 라고 생각되어서요)

**Comment by jaewonlee-728** [comment]
안녕하세요, 질문주신 내용에 대한 답변은 아래와 같습니다. 

먼저 말씀주신대로 리뷰데이터를 이런식으로 활용할 수 있다는 것이 실습의 목적이고, 추천시스템에 적용하기 위해 텍스트 데이터를 다뤄보는 것 또한 실습의 목적입니다. 리뷰데이터로 추천시스템의 성능을 향상시키는 방법은 다양하다고 생각합니다. 예를 들어, 리뷰를 작성한 유저 정보를 활용하여 유저정보를 활용한 추천시스템을 만들 때 user profile을 더 풍부하게 만들 수 있습니다. 또한 다양한 리뷰를 바탕으로 text mining기법을 활용해서 추천시스템에 활용할 수도 있을 것 같습니다. 
주어진 평점 또는 별점 등 정형화된 데이터만 활용하는 것이 아니라 텍스트와 같은 비정형 데이터를 활용함으로써 추천시스템의 성능을 높이고자 하는 다양한 연구가 진행되고 있습니다. 이점 또한 참고로 찾아보시면 더욱 도움이 될 것 같습니다. 

질문 주셔서 감사합니다. 추가로 궁금하신 부분 있으시면 말씀 부탁드리겠습니다.

**Comment by hongym7** [comment]
네 이해가 갑니다 감사합니다.
