### ISSUE TITLE
wide & deep, deepFM 실습관련 질문

### ISSUE THREAD

**Issue by brianWang-seoul** [jaewonlee-728/fastcampus-RecSys#6]
강사님 안녕하세요.
강의내용을 잘 들었습니다. 

제가 이쪽 분야 관련해서 전문가가 아니다보니 
강의 내용중에 음악 추천부분만 추천 시스템의 대한 이해가 되는 상황입니다. (TF-IDF를 이용한 tag-vector를 만들고, 만들어진 vetor값들을 코사인-유사도로 추천 리스트 출력)

아쉬운 부분은  
wide & deep, deepFM을 적용한 모델을 가지고 음악 추천 강좌처럼 input값(질의정보)을 넣었을때 해당되는 추천 리스트를 출력해주는 예제가 있었으면 저와 같은 초보들에게 많은 도움이 되었을것 같습니다. 

혹시 이 부분에 대해서 요청드려도 될까요?

**Comment by jaewonlee-728** [comment]
안녕하세요, 강의 들어주셔서 감사합니다.
강의 듣고 피드백 남겨주신 점 반영해서 다음 강의는 좀더 많은 예제와 풍부한 컨텐츠를 다룰 수 있도록 준비하겠습니다. 감사합니다.
